[env]
RUSTFLAGS="-Awarnings"

[tasks.clear]
description = "Clear window"
script = ['''
#!/bin/bash
clear >$(tty)
echo ""
''']

[tasks.stest]
description = "Single test"
script = ['''
#!/bin/bash
cargo +1.70-x86_64-unknown-linux-gnu test -r --features local --bin $1 --all $2 -- --nocapture
''']
dependencies = ["clear"]

[tasks.mtest]
description = "Multi test"
script = ['''
#!/bin/bash
cargo +1.70-x86_64-unknown-linux-gnu test -r --features local --bin $1 --all multi -- --nocapture
''']
dependencies = ["clear"]

[tasks.run]
description = "Run and visualize"
script = ['''
#!/bin/bash
cargo +1.70-x86_64-unknown-linux-gnu run -r --features local --bin $1 < tools/$1/in$3/$2.txt > tools/$1/out$3/$2.txt
#cp tools/$1/in/$2.txt in
#cp tools/$1/out/$2.txt out
cargo +1.74-x86_64-unknown-linux-gnu run -r --manifest-path tools/$1/Cargo.toml --bin score tools/$1/in$3/$2.txt tools/$1/out$3/$2.txt
''']
dependencies = ["clear"]

[tasks.interactive]
description = "Interactive run and visualize"
script = ['''
#!/bin/bash
cargo +1.74-x86_64-unknown-linux-gnu run -r --manifest-path tools/$1/Cargo.toml --bin tester cargo +1.70-x86_64-unknown-linux-gnu run -r --features local --bin $1$3 < tools/$1/in/$2.txt > tools/$1/out/$2.txt
cp tools/$1/in/$2.txt in
cp tools/$1/out/$2.txt out
cargo +1.74-x86_64-unknown-linux-gnu run -r --manifest-path tools/$1/Cargo.toml --bin vis tools/$1/in/$2.txt tools/$1/out/$2.txt
''']
dependencies = ["clear"]


[tasks.submit]
description = "Make submit file"
script = ['''
#!/bin/bash
bash shell/submit.sh $1 $2
''']

[tasks.vis]
description = "Visualize"
script = ['''
#!/bin/bash
cargo +1.74-x86_64-unknown-linux-gnu run -r --manifest-path tools/$1/Cargo.toml --bin vis tools/$1/in/$2.txt tools/$1/out/$2.txt
''']

[tasks.gen]
description = "Generate input"
script = ['''
#!/bin/bash
cd tools/$1
rm seeds.txt
touch seeds.txt
for i in $(seq 0 $(($2-1))); do
    echo $i >> seeds.txt
done
cargo +1.74-x86_64-unknown-linux-gnu run -r --manifest-path Cargo.toml --bin gen seeds.txt
cd ../..
''']